sudo: required
services: 
  - docker
  
before_install:
  -docker build -t allotsys/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run allotsys/react-test npm test -- --coverage
  
after_success:
  - docker build -t allotsys/multi-client ./client
  - docker build -t allotsys/multi-nginx ./nginx
  - docker build -t allotsys/multi-server ./server
  - docker build -t allotsys/multi-worker ./worker
  # Log into the docker CLI
  - ECHO "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  DOCKER_ID
  # Take those images and push them to docker hub
  - docker push allotsys/multi-client
  - docker push allotsys/multi-nginx
  - docker push allotsys/multi-server
  - docker push allotsys/multi-worker