sudo: required
services: 
  - docker
  
before_install:
  - docker build -t allotsys/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run allotsys/react-test npm test -- --coverage
  
after_success:
  - docker build -t allotsys/multi-client ./client
  - docker build -t allotsys/multi-nginx ./nginx
  - docker build -t allotsys/multi-server ./server
  - docker build -t allotsys/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push allotsys/multi-client
  - docker push allotsys/multi-nginx
  - docker push allotsys/multi-server
  - docker push allotsys/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-202086208544
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY